# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 823)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_3 = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(parent=self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.frame_3 = EndviewView(parent=self.splitter)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = CScanView(parent=self.splitter)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setObjectName("frame_4")
        self.splitter_2 = QtWidgets.QSplitter(parent=self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_5 = VolumeView(parent=self.splitter_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = AScanView(parent=self.splitter_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 22))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(parent=self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuOverlay = QtWidgets.QMenu(parent=self.menubar)
        self.menuOverlay.setObjectName("menuOverlay")
        self.menuInf_rence = QtWidgets.QMenu(parent=self.menubar)
        self.menuInf_rence.setObjectName("menuInf_rence")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioncharger_npz = QtGui.QAction(parent=MainWindow)
        self.actioncharger_npz.setObjectName("actioncharger_npz")
        self.actionopen_nde = QtGui.QAction(parent=MainWindow)
        self.actionopen_nde.setObjectName("actionopen_nde")
        self.actionSauvegarder = QtGui.QAction(parent=MainWindow)
        self.actionSauvegarder.setObjectName("actionSauvegarder")
        self.actionParam_tres = QtGui.QAction(parent=MainWindow)
        self.actionParam_tres.setObjectName("actionParam_tres")
        self.actionQuitter = QtGui.QAction(parent=MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionParam_tres_2 = QtGui.QAction(parent=MainWindow)
        self.actionParam_tres_2.setObjectName("actionParam_tres_2")
        self.actionnnunet = QtGui.QAction(parent=MainWindow)
        self.actionnnunet.setObjectName("actionnnunet")
        self.menuFichier.addAction(self.actionopen_nde)
        self.menuFichier.addAction(self.actionSauvegarder)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionParam_tres)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuOverlay.addAction(self.actioncharger_npz)
        self.menuOverlay.addAction(self.actionParam_tres_2)
        self.menuInf_rence.addAction(self.actionnnunet)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuOverlay.menuAction())
        self.menubar.addAction(self.menuInf_rence.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuOverlay.setTitle(_translate("MainWindow", "Overlay"))
        self.menuInf_rence.setTitle(_translate("MainWindow", "Inférence"))
        self.actioncharger_npz.setText(_translate("MainWindow", "Charger un fichier .npz/.npy"))
        self.actionopen_nde.setText(_translate("MainWindow", "Ouvrir un fichier .nde"))
        self.actionSauvegarder.setText(_translate("MainWindow", "Sauvegarder"))
        self.actionParam_tres.setText(_translate("MainWindow", "Paramètres"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionParam_tres_2.setText(_translate("MainWindow", "Paramètres overlay"))
        self.actionnnunet.setText(_translate("MainWindow", "nnunet"))
from views.ascan_view import AScanView
from views.cscan_view import CScanView
from views.endview_view import EndviewView
from views.volume_view import VolumeView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
